# Generated by Django 2.2.9 on 2020-06-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('access_level', models.IntegerField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('volume', models.CharField(max_length=20)),
                ('os_type', models.CharField(max_length=100)),
                ('used_programs', models.CharField(max_length=100)),
                ('system_requirements', models.TextField()),
                ('program_description', models.TextField()),
                ('usage_description', models.TextField()),
                ('date', models.DateField()),
                ('agreement_id', models.IntegerField()),
            ],
            options={
                'db_table': 'repositories',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('volume', models.CharField(max_length=20)),
                ('os_type', models.CharField(max_length=100)),
                ('used_programs', models.CharField(max_length=100)),
                ('system_requirements', models.TextField()),
                ('program_description', models.TextField()),
                ('usage_description', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employees')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('lawyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_id', to='main.Employees')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_id', to='main.Employees')),
            ],
            options={
                'db_table': 'agreements',
            },
        ),
    ]
