# Generated by Django 2.2.9 on 2020-06-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_id', to='main.Requests'),
        ),
    ]
